version: "3.8"
services:
    jmeter:
        image: bbuzens/jmeter:latest
        volumes:
            - "./scripts:/var/opt/apache-jmeter/scripts"
            - "./log:/var/opt/apache-jmeter/log"
            - "./results:/var/opt/apache-jmeter/results"
            - "./data:/var/opt/apache-jmeter/data"
